import {render,screen,fireEvent,waitFor,act} from '@testing-library/react';import {MemoryRouter} from 'react-router-dom';import {vi,beforeEach} from 'vitest';import App from '../src/App';import * as api from '../src/services/api';
vi.mock('../src/services/api');
const admin={id:'admin',username:'admin-test',fullName:'Test Admin',email:'admin@example.test',role:'ADMIN',active:true};
const staff={...admin,id:'staff',username:'staff-test',fullName:'Test Staff',role:'BLOOD_BANK_USER'};
const researcher={...admin,id:'research',username:'research-test',fullName:'Test Researcher',role:'RESEARCH_STUDENT'};
beforeEach(()=>{vi.resetAllMocks();api.getCurrentUser.mockRejectedValue({response:{status:401}});api.getInventory.mockResolvedValue([]);api.getRequests.mockResolvedValue([]);api.getUsers.mockResolvedValue([admin,staff]);api.getResearchSummary.mockResolvedValue({totalDonations:1,donationsByBloodType:[{bloodType:'A+',donations:1,units:2}],inventory:[{bloodType:'A+',unitsAvailable:2,reservedUnits:0}]});api.getResearchDonations.mockResolvedValue({items:[{bloodType:'A+',donationYear:2026,unitsDonated:2,status:'AVAILABLE',donorName:'Hidden PHI',notes:'Hidden notes'}],pagination:{page:1,pages:1}});api.getAuditLogs.mockResolvedValue({items:[],pagination:{page:1,pages:0,total:0,limit:10}});});
function show(path='/login'){return render(<MemoryRouter initialEntries={[path]}><App/></MemoryRouter>);}
async function fillLogin(){await screen.findByLabelText('Username / Email');fireEvent.change(screen.getByLabelText('Username / Email'),{target:{value:'admin-test'}});fireEvent.change(screen.getByLabelText('Password'),{target:{value:'Aa1'+crypto.randomUUID()}});await act(async()=>{fireEvent.click(screen.getByRole('button',{name:'Sign In'}));});}
test('Login renders username and password',async()=>{show();expect(await screen.findByLabelText('Password')).toHaveAttribute('type','password');});
test('Valid login reveals role-aware admin navigation',async()=>{api.login.mockResolvedValue(admin);show();await fillLogin();expect(await screen.findByText('Test Admin')).toBeInTheDocument();expect(screen.getByRole('link',{name:'Users'})).toBeInTheDocument();});
test('Invalid login uses a generic message',async()=>{api.login.mockRejectedValue({response:{status:401}});show();await fillLogin();expect(await screen.findByRole('alert')).toHaveTextContent('Invalid username or password.');expect(screen.getByLabelText('Password')).toHaveValue('');});
test('Logout makes protected pages inaccessible',async()=>{api.getCurrentUser.mockResolvedValue(admin);api.logout.mockResolvedValue({});show('/inventory');fireEvent.click(await screen.findByRole('button',{name:'Logout'}));expect(await screen.findByRole('heading',{name:'Sign In'})).toBeInTheDocument();});
test('Unauthenticated protected route redirects to login',async()=>{show('/admin/users');expect(await screen.findByRole('heading',{name:'Sign In'})).toBeInTheDocument();});
test('Research user cannot manually open admin route',async()=>{api.getCurrentUser.mockResolvedValue(researcher);show('/admin/users');expect(await screen.findByRole('heading',{name:'Access Denied'})).toBeInTheDocument();expect(api.getUsers).not.toHaveBeenCalled();});
test('Operator navigation retains operations and hides admin links',async()=>{api.getCurrentUser.mockResolvedValue(staff);show('/inventory');expect(await screen.findByRole('link',{name:'Donate'})).toBeInTheDocument();expect(screen.getByRole('link',{name:'Emergency'})).toBeInTheDocument();expect(screen.queryByRole('link',{name:'Users'})).not.toBeInTheDocument();expect(screen.queryByRole('link',{name:'Audit Trail'})).not.toBeInTheDocument();});
test('Research navigation and data contain no PHI',async()=>{api.getCurrentUser.mockResolvedValue(researcher);show('/research');expect(await screen.findByRole('heading',{name:'De-identified Donation Records'})).toBeInTheDocument();expect(screen.queryByText('Hidden PHI')).not.toBeInTheDocument();expect(screen.queryByText('Hidden notes')).not.toBeInTheDocument();expect(screen.queryByRole('link',{name:'Donate'})).not.toBeInTheDocument();});
test('Admin user management creates accounts',async()=>{api.getCurrentUser.mockResolvedValue(admin);api.createUser.mockResolvedValue(staff);show('/admin/users');await screen.findByRole('heading',{name:'User Management'});for(const[label,value]of [['Username','new-user'],['Full name','New User'],['Email','new@example.test'],['Initial password','Aa1'+crypto.randomUUID()]])fireEvent.change(screen.getByLabelText(label),{target:{value}});fireEvent.click(screen.getByRole('button',{name:'Create User'}));await waitFor(()=>expect(api.createUser).toHaveBeenCalledWith(expect.objectContaining({username:'new-user',role:'BLOOD_BANK_USER'})));expect(await screen.findByRole('alert')).toHaveTextContent('User created.');});
test('Admin retains Part 11 exports',async()=>{api.getCurrentUser.mockResolvedValue(admin);show('/part11');expect(await screen.findByRole('button',{name:'Download BECS Metadata'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Download Audit Trail'})).toBeInTheDocument();});
test('Admin retains Audit Trail page',async()=>{api.getCurrentUser.mockResolvedValue(admin);show('/audit');expect(await screen.findByText('No audit records found')).toBeInTheDocument();});
test('Expired authentication event redirects to login',async()=>{api.getCurrentUser.mockResolvedValue(admin);show('/inventory');await screen.findByRole('button',{name:'Logout'});act(()=>window.dispatchEvent(new Event('bloodcare-auth-expired')));expect(await screen.findByRole('heading',{name:'Sign In'})).toBeInTheDocument();});
