import {render,screen,fireEvent,waitFor} from '@testing-library/react'; import {vi,beforeEach} from 'vitest'; import EmergencyPage from '../src/pages/EmergencyPage'; import * as api from '../src/services/api';
vi.mock('../src/services/api');
const result={_id:'e1',eventName:'Drill',createdAt:'2026-01-01',numberOfCasualties:2,estimatedUnitsRequired:2,severity:'CRITICAL',status:'SIMULATED',workflowStatus:'SIMULATED',allocationStatus:'CRITICAL_SHORTAGE',event:{casualties:2},totalRequested:2,totalAllocated:2,shortage:2,warnings:['Insufficient compatible emergency inventory'],allocation:[{bloodType:'O-',availableBefore:7,unitsAllocated:2,availableAfter:5}]};
beforeEach(()=>{vi.clearAllMocks();api.confirmEmergency.mockResolvedValue({...result,status:'CONFIRMED'});api.getEmergencyEvents.mockReturnValue(new Promise(()=>{}));});
function fill(){fireEvent.change(screen.getByLabelText('Number of Casualties'),{target:{value:'2'}});}
test('emergency page renders with academic disclaimer and loading history',()=>{render(<EmergencyPage/>);expect(screen.getByRole('heading',{name:'Mass Casualty Emergency'})).toBeInTheDocument();expect(screen.getByText(/must not be used for clinical/i)).toBeInTheDocument();expect(screen.getByRole('status')).toBeInTheDocument();});
test('form validates required values',()=>{render(<EmergencyPage/>);fireEvent.change(screen.getByLabelText('Number of Casualties'),{target:{value:'0'}});fireEvent.click(screen.getByRole('button',{name:/allocate emergency/i}));expect(screen.getByRole('alert')).toHaveTextContent('positive casualty');});
test('all unknown mode does not ask for blood types',()=>{render(<EmergencyPage/>);expect(screen.queryByText('Casualty Blood Types')).not.toBeInTheDocument();});
test('simulation renders dashboard and shortage warning',async()=>{api.simulateEmergency.mockResolvedValue(result);render(<EmergencyPage/>);fill();fireEvent.click(screen.getByRole('button',{name:/allocate emergency/i}));expect(await screen.findByText(/Only 2 of the requested 2/)).toBeInTheDocument();expect(screen.getAllByText('2',{selector:'.emergency-summary strong'})).toHaveLength(4);await waitFor(()=>expect(api.confirmEmergency).toHaveBeenCalledWith('e1'));});
test('shows simulation API error',async()=>{api.simulateEmergency.mockRejectedValue({response:{data:{message:'Database unavailable'}}});render(<EmergencyPage/>);fill();fireEvent.click(screen.getByRole('button',{name:/allocate emergency/i}));expect(await screen.findByRole('alert')).toHaveTextContent('Database unavailable');});
test('shows simulation loading state',async()=>{api.simulateEmergency.mockReturnValue(new Promise(()=>{}));render(<EmergencyPage/>);fill();fireEvent.click(screen.getByRole('button',{name:/allocate emergency/i}));expect(screen.getByRole('button',{name:'Allocating…'})).toBeDisabled();});
test('successful confirmation updates status and hides confirmation',async()=>{api.simulateEmergency.mockResolvedValue(result);api.confirmEmergency.mockResolvedValue({...result,status:'CONFIRMED',workflowStatus:'CONFIRMED'});render(<EmergencyPage/>);fill();fireEvent.click(screen.getByRole('button',{name:/allocate emergency/i}));await waitFor(()=>expect(api.confirmEmergency).toHaveBeenCalledWith('e1'));expect(screen.getByRole('alert')).toHaveTextContent('confirmed');expect(screen.queryByRole('button',{name:/confirm emergency/i})).not.toBeInTheDocument();});
test('confirmation API error is visible',async()=>{api.simulateEmergency.mockResolvedValue(result);api.confirmEmergency.mockRejectedValue({response:{data:{message:'Unable to confirm emergency allocation.'}}});render(<EmergencyPage/>);fill();fireEvent.click(screen.getByRole('button',{name:/allocate emergency/i}));expect(await screen.findByRole('alert')).toHaveTextContent('Unable to confirm');});
test.each(['','-1','1.5','text'])('invalid casualty count %s rejected',value=>{render(<EmergencyPage/>);fireEvent.change(screen.getByLabelText('Number of Casualties'),{target:{value}});fireEvent.click(screen.getByRole('button',{name:/allocate emergency/i}));expect(screen.getByRole('alert')).toHaveTextContent('positive casualty');expect(api.simulateEmergency).not.toHaveBeenCalled();});
test('zero inventory shows explicit message and hides confirmation',async()=>{api.simulateEmergency.mockResolvedValue({...result,totalAllocated:0,shortage:2,allocation:[{bloodType:'O-',availableBefore:0,unitsAllocated:0,availableAfter:0}]});render(<EmergencyPage/>);fill();fireEvent.click(screen.getByRole('button',{name:/allocate emergency/i}));expect(await screen.findByText('No O-negative units are currently available.')).toBeInTheDocument();expect(screen.queryByRole('button',{name:/confirm emergency/i})).not.toBeInTheDocument();});
test('form has only count and sends count-only payload',async()=>{api.simulateEmergency.mockResolvedValue(result);const {container}=render(<EmergencyPage/>);expect(container.querySelectorAll('form input,form select,form textarea')).toHaveLength(1);fill();fireEvent.click(screen.getByRole('button',{name:/allocate emergency/i}));await waitFor(()=>expect(api.simulateEmergency).toHaveBeenCalledWith({numberOfCasualties:2}));expect(container.querySelectorAll('.emergency-summary article')).toHaveLength(6);});
