import {render,screen,fireEvent,waitFor} from '@testing-library/react'; import {vi,beforeEach} from 'vitest'; import EmergencyPage from '../src/pages/EmergencyPage'; import * as api from '../src/services/api';
vi.mock('../src/services/api');
const result={_id:'e1',eventName:'Drill',createdAt:'2026-01-01',numberOfCasualties:2,estimatedUnitsRequired:4,severity:'CRITICAL',status:'SIMULATED',workflowStatus:'SIMULATED',allocationStatus:'CRITICAL_SHORTAGE',event:{casualties:2},totalRequested:4,totalAllocated:2,shortage:2,warnings:['Insufficient compatible emergency inventory'],allocation:[{bloodType:'O-',availableBefore:7,unitsAllocated:2,availableAfter:5}]};
beforeEach(()=>{vi.clearAllMocks();api.getEmergencyEvents.mockReturnValue(new Promise(()=>{}));});
function fill(){fireEvent.change(screen.getByLabelText('Event Name'),{target:{value:'Drill'}});fireEvent.change(screen.getByLabelText('Number of Casualties'),{target:{value:'2'}});fireEvent.change(screen.getByLabelText('Estimated RBC Units Required'),{target:{value:'4'}});}
test('emergency page renders with academic disclaimer and loading history',()=>{render(<EmergencyPage/>);expect(screen.getByRole('heading',{name:'Mass Casualty Emergency'})).toBeInTheDocument();expect(screen.getByText(/must not be used for clinical/i)).toBeInTheDocument();expect(screen.getByRole('status')).toBeInTheDocument();});
test('form validates required values',()=>{render(<EmergencyPage/>);fireEvent.change(screen.getByLabelText('Number of Casualties'),{target:{value:'0'}});fireEvent.click(screen.getByRole('button',{name:/simulate emergency/i}));expect(screen.getByRole('alert')).toHaveTextContent('positive casualty');});
test('all unknown mode does not ask for blood types',()=>{render(<EmergencyPage/>);expect(screen.queryByText('Casualty Blood Types')).not.toBeInTheDocument();});
test('partially known mode renders casualty selectors and validates mixture',()=>{render(<EmergencyPage/>);fill();fireEvent.change(screen.getByLabelText('Blood Type Status'),{target:{value:'PARTIALLY_KNOWN'}});expect(screen.getByLabelText('Casualty 1 blood type')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:/simulate emergency/i}));expect(screen.getByRole('alert')).toHaveTextContent('at least one known');});
test('all known mode supplies existing blood types',()=>{render(<EmergencyPage/>);fill();fireEvent.change(screen.getByLabelText('Blood Type Status'),{target:{value:'ALL_KNOWN'}});expect(screen.getByLabelText('Casualty 1 blood type')).toHaveValue('O-');expect(screen.getByLabelText('Casualty 2 blood type')).toHaveValue('O-');});
test('simulation renders dashboard and shortage warning',async()=>{api.simulateEmergency.mockResolvedValue(result);render(<EmergencyPage/>);fill();fireEvent.click(screen.getByRole('button',{name:/simulate emergency/i}));expect(await screen.findByText(/CRITICAL: Insufficient/i)).toBeInTheDocument();expect(screen.getAllByText('2',{selector:'.emergency-summary strong'})).toHaveLength(3);expect(screen.getByRole('button',{name:/confirm emergency/i})).toBeInTheDocument();});
test('shows simulation API error',async()=>{api.simulateEmergency.mockRejectedValue({response:{data:{message:'Database unavailable'}}});render(<EmergencyPage/>);fill();fireEvent.click(screen.getByRole('button',{name:/simulate emergency/i}));expect(await screen.findByRole('alert')).toHaveTextContent('Database unavailable');});
test('shows simulation loading state',async()=>{api.simulateEmergency.mockReturnValue(new Promise(()=>{}));render(<EmergencyPage/>);fill();fireEvent.click(screen.getByRole('button',{name:/simulate emergency/i}));expect(screen.getByRole('button',{name:'Simulating…'})).toBeDisabled();});
test('successful confirmation updates status and hides confirmation',async()=>{api.simulateEmergency.mockResolvedValue(result);api.confirmEmergency.mockResolvedValue({...result,status:'CONFIRMED',workflowStatus:'CONFIRMED'});render(<EmergencyPage/>);fill();fireEvent.click(screen.getByRole('button',{name:/simulate emergency/i}));fireEvent.click(await screen.findByRole('button',{name:/confirm emergency/i}));await waitFor(()=>expect(api.confirmEmergency).toHaveBeenCalledWith('e1'));expect(screen.getByRole('alert')).toHaveTextContent('confirmed');expect(screen.queryByRole('button',{name:/confirm emergency/i})).not.toBeInTheDocument();});
test('confirmation API error is visible',async()=>{api.simulateEmergency.mockResolvedValue(result);api.confirmEmergency.mockRejectedValue(new Error('fail'));render(<EmergencyPage/>);fill();fireEvent.click(screen.getByRole('button',{name:/simulate emergency/i}));fireEvent.click(await screen.findByRole('button',{name:/confirm emergency/i}));expect(await screen.findByRole('alert')).toHaveTextContent('Unable to confirm');});
