import {useEffect,useState} from 'react';import Loading from '../components/Loading';import StatusMessage from '../components/StatusMessage';import {confirmEmergency,getEmergencyEvent,getEmergencyEvents,simulateEmergency} from '../services/api';
export default function EmergencyPage(){
 const[count,setCount]=useState(1);const[result,setResult]=useState(null);const[history,setHistory]=useState(null);const[selected,setSelected]=useState(null);const[error,setError]=useState('');const[success,setSuccess]=useState('');const[loading,setLoading]=useState(false);const[confirming,setConfirming]=useState(false);
 useEffect(()=>{getEmergencyEvents().then(setHistory).catch(()=>setHistory([]));},[]);
 async function submit(event){event.preventDefault();setError('');setSuccess('');const number=Number(count);if(count===''||!Number.isInteger(number)||number<1||number>1000){setError('Enter a positive casualty count: an integer between 1 and 1000.');return;}try{setLoading(true);setResult(null);let data=await simulateEmergency({numberOfCasualties:number});setResult(data);setHistory(rows=>[data,...(rows||[])]);if(data.totalAllocated>0){data=await confirmEmergency(data._id);setResult(data);setHistory(rows=>(rows||[]).map(item=>item._id===data._id?data:item));setSuccess('Emergency allocation confirmed. O-negative inventory was updated.');}else{setSuccess('No O-negative units are currently available. Inventory was not changed.');}}catch(err){setError(err.response?.data?.errors?.join(', ')||err.response?.data?.message||'Unable to simulate emergency allocation.');}finally{setLoading(false);}}
 async function confirm(){setError('');setSuccess('');try{setConfirming(true);const data=await confirmEmergency(result._id);setResult(data);setSuccess('Emergency allocation confirmed. O-negative inventory was updated.');setHistory(rows=>(rows||[]).map(item=>item._id===data._id?data:item));}catch(err){setError(err.response?.data?.message||'Unable to confirm emergency allocation.');}finally{setConfirming(false);}}
 async function open(id){try{setSelected(await getEmergencyEvent(id));}catch{setError('Unable to load emergency event details.');}}
 return <div className="container page emergency-page"><header className="page-header emergency-header"><span className="eyebrow">🚨 Academic inventory simulation</span><h1>Mass Casualty Emergency</h1><p>One O-negative RBC unit per casualty. Only O-negative units are allocated; no substitutes.</p></header><div className="alert alert-dark emergency-disclaimer" role="note"><strong>Academic prototype – Emergency recommendations are for simulation only and must not be used for clinical decision-making.</strong></div><div className="row g-5"><div className="col-lg-5"><form className="form-card" onSubmit={submit} noValidate><label className="form-label" htmlFor="casualties">Number of Casualties</label><input id="casualties" type="number" min="1" max="1000" step="1" required disabled={loading||confirming} className="form-control" value={count} onChange={event=>{setCount(event.target.value);setResult(null);setSuccess('');}}/><p className="mt-3">1 casualty = 1 O-negative RBC unit required. Allocation automatically confirms and deducts the allocated units from inventory.</p><StatusMessage error={error} success={success}/><button className="btn btn-emergency w-100 mt-4" disabled={loading||confirming}>{loading?'Allocating…':'Allocate Emergency Units'}</button></form></div><div className="col-lg-7">{loading?<Loading/>:result?<EmergencyDashboard result={result} onConfirm={confirm} confirming={confirming}/>:<div className="empty-state emergency-empty"><div className="drop">🚨</div><h2>Emergency plan appears here</h2><p>Allocation updates O-negative inventory automatically after authorized confirmation.</p></div>}</div></div><EmergencyHistory rows={history} selected={selected} onOpen={open} onClose={()=>setSelected(null)}/></div>;
}
function EmergencyDashboard({result,onConfirm,confirming}){
 const stock=result.allocation.find(item=>item.bloodType==='O-');const message=result.totalAllocated===0?'No O-negative units are currently available.':result.shortage>0?`Only ${result.totalAllocated} of the requested ${result.totalRequested} O-negative units are available. Missing: ${result.shortage} units.`:'The required O-negative units are available.';
 return <section className="emergency-dashboard" aria-live="polite"><div className="results-heading"><span>🚨 O-NEGATIVE ONLY</span></div><div className={`alert ${result.totalAllocated===0?'alert-danger':result.shortage?'alert-warning':'alert-success'}`}>{message}</div><div className="emergency-summary">{[['Number of Casualties',result.event.casualties],['Requested O− Units',result.totalRequested],['Available O− Before Allocation',stock.availableBefore],['Allocated O− Units',result.totalAllocated],['Shortage',result.shortage],['O− Remaining After Allocation',stock.availableAfter]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><h2>Emergency Inventory — O−</h2><div className="table-responsive table-card"><table className="table"><thead><tr><th>Blood Type</th><th>Before</th><th>Allocated</th><th>After</th></tr></thead><tbody><tr><td><span className="type-badge">O−</span></td><td>{stock.availableBefore}</td><td>{stock.unitsAllocated}</td><td>{stock.availableAfter}</td></tr></tbody></table></div><div className="warning-list"><h2>Review</h2><ul>{result.warnings.map(item=><li key={item}>⚠️ {item}</li>)}</ul></div>{result.status==='SIMULATED'&&result.totalAllocated>0&&<div className="confirm-panel"><strong>⚠️ Confirmation deducts only the allocated O-negative units.</strong><button type="button" className="btn btn-danger" disabled={confirming} onClick={onConfirm}>{confirming?'Confirming…':'Confirm Emergency Allocation'}</button></div>}</section>;
}
function EmergencyHistory({rows,selected,onOpen,onClose}){return <section className="mt-5"><div className="section-heading"><span className="eyebrow">Audit trail</span><h2>Emergency History</h2></div>{rows===null?<Loading/>:<div className="table-responsive table-card"><table className="table"><thead><tr><th>Event</th><th>Date</th><th>Casualties</th><th>Requested</th><th>Allocated</th><th>Shortage</th><th>Severity</th><th>Status</th></tr></thead><tbody>{rows.map(x=><tr key={x._id}><td><button className="btn btn-link p-0" onClick={()=>onOpen(x._id)}>{x.eventName}</button></td><td>{new Date(x.createdAt).toLocaleDateString()}</td><td>{x.numberOfCasualties}</td><td>{x.estimatedUnitsRequired}</td><td>{x.totalAllocated}</td><td>{x.shortage}</td><td>{x.severity}</td><td>{x.status}</td></tr>)}</tbody></table></div>}{selected&&<div className="event-detail"><button className="btn-close float-end" aria-label="Close event details" onClick={onClose}/><h3>{selected.eventName}</h3><p>{selected.allocationStatus.replaceAll('_',' ')} · {selected.totalAllocated} allocated · {selected.shortage} shortage</p><ul>{selected.warnings.map(x=><li key={x}>{x}</li>)}</ul></div>}</section>}
