const crypto=require('node:crypto');const bcrypt=require('bcryptjs');const User=require('../models/User');const Session=require('../models/AuthSession');const Lock=require('../models/AdminLock');const auth=require('./authService');const audit=require('./auditService');
function httpError(message,status=400){const error=new Error(message);error.status=status;return error;}
async function withAdminLock(fn){const owner=crypto.randomUUID();let lock;try{lock=await Lock.findOneAndUpdate({_id:'admin-management',expiresAt:{$lt:new Date()}},{$set:{owner,expiresAt:new Date(Date.now()+60000)}},{upsert:true,new:true});}catch(error){if(error.code===11000)throw httpError('Another administrator update is in progress. Try again.',409);throw error;}try{if(lock.owner!==owner)throw httpError('Administrator update in progress',409);return await fn();}finally{await Lock.deleteOne({_id:'admin-management',owner});}}
async function list(){return(await User.find().sort({createdAt:-1})).map(auth.safeUser);}
async function create(data){if(!auth.passwordValid(data.password))throw httpError('Password must have 8–72 characters, uppercase, lowercase and a number.');const passwordHash=await bcrypt.hash(data.password,12);const user=await User.create({username:data.username,fullName:data.fullName,email:data.email,role:data.role,active:true,passwordHash});await audit.createAuditLog({action:'USER_CREATED',entityType:'USER',entityId:String(user._id),description:'Application user created',newValue:{username:user.username,role:user.role,active:true}});return auth.safeUser(user);}
async function update(id,data){return withAdminLock(async()=>{const user=await User.findById(id);if(!user)throw httpError('User not found',404);if(user.active&&user.role==='ADMIN'&&(data.active===false||(data.role&&data.role!=='ADMIN'))&&await User.countDocuments({active:true,role:'ADMIN'})<=1)throw httpError('Cannot remove the last active administrator.',409);const old={role:user.role,active:user.active};for(const key of ['fullName','email','role','active'])if(data[key]!==undefined)user[key]=data[key];await user.save();if(old.role!==user.role){await Session.deleteMany({userId:user._id});await audit.createAuditLog({action:'USER_ROLE_CHANGED',entityType:'USER',entityId:String(user._id),description:'User role changed',oldValue:{role:old.role},newValue:{role:user.role}});}if(old.active!==user.active){await Session.deleteMany({userId:user._id});await audit.createAuditLog({action:user.active?'USER_ACTIVATED':'USER_DEACTIVATED',entityType:'USER',entityId:String(user._id),description:'User account status changed',oldValue:{active:old.active},newValue:{active:user.active}});}return auth.safeUser(user);});}
async function resetPassword(id,password){if(!auth.passwordValid(password))throw httpError('Password must have 8–72 characters, uppercase, lowercase and a number.');return withAdminLock(async()=>{const user=await User.findById(id);if(!user)throw httpError('User not found',404);user.passwordHash=await bcrypt.hash(password,12);await user.save();await Session.deleteMany({userId:user._id});await audit.createAuditLog({action:'USER_PASSWORD_RESET',entityType:'USER',entityId:String(user._id),description:'Administrator reset a user password'});return auth.safeUser(user);});}
async function seedAdmin(data){return withAdminLock(async()=>{if(await User.exists({role:'ADMIN',active:true}))return null;if(await User.exists({$or:[{username:data.username.toLowerCase()},{email:data.email.toLowerCase()}]}))throw httpError('Initial administrator identity is already in use.');return create({...data,role:'ADMIN'});});}
module.exports={list,create,update,resetPassword,seedAdmin};
