const mongoose=require('mongoose'); const {MongoMemoryServer}=require('mongodb-memory-server'); const Inventory=require('../models/BloodInventory'); const EmergencyEvent=require('../models/EmergencyEvent'); const service=require('../services/emergencyAllocationService');
let mongo; const payload={eventName:'Standalone drill',numberOfCasualties:1,bloodTypeStatus:'ALL_UNKNOWN',estimatedUnitsRequired:2,severity:'CRITICAL',casualtyData:[{casualtyNumber:1,bloodType:'UNKNOWN'}]};
beforeAll(async()=>{mongo=await MongoMemoryServer.create();await mongoose.connect(mongo.getUri());},60000);
afterAll(async()=>{await mongoose.disconnect();await mongo.stop();},60000);
beforeEach(async()=>{await Promise.all([Inventory.deleteMany({}),EmergencyEvent.deleteMany({})]);await Inventory.create({bloodType:'O-',unitsAvailable:10,reservedUnits:0});});
test('standalone confirmation updates inventory without requiring transactions',async()=>{const simulated=await service.simulate(payload);const confirmed=await service.confirm(simulated._id);expect(confirmed.status).toBe('CONFIRMED');expect((await Inventory.findOne({bloodType:'O-'})).unitsAvailable).toBe(8);});
test('standalone confirmation prevents duplicate decrement',async()=>{const simulated=await service.simulate(payload);await service.confirm(simulated._id);await expect(service.confirm(simulated._id)).rejects.toMatchObject({status:409});expect((await Inventory.findOne({bloodType:'O-'})).unitsAvailable).toBe(8);});
test('standalone confirmation rejects stale inventory and releases event lock',async()=>{const simulated=await service.simulate(payload);await Inventory.updateOne({bloodType:'O-'},{$inc:{unitsAvailable:1}});await expect(service.confirm(simulated._id)).rejects.toMatchObject({status:409});expect((await EmergencyEvent.findById(simulated._id)).status).toBe('SIMULATED');expect((await Inventory.findOne({bloodType:'O-'})).unitsAvailable).toBe(11);});
test('count-only simulation is read-only and confirmation exhausts only O-negative',async()=>{await Inventory.updateOne({bloodType:'O-'},{$set:{unitsAvailable:6}});await Inventory.create({bloodType:'O+',unitsAvailable:100,reservedUnits:0});const simulated=await service.simulate({numberOfCasualties:10});expect(simulated.totalRequested).toBe(10);expect(simulated.totalAllocated).toBe(6);expect(simulated.shortage).toBe(4);expect((await Inventory.findOne({bloodType:'O-'})).unitsAvailable).toBe(6);await service.confirm(simulated._id);expect((await Inventory.findOne({bloodType:'O-'})).unitsAvailable).toBe(0);expect((await Inventory.findOne({bloodType:'O+'})).unitsAvailable).toBe(100);await expect(service.confirm(simulated._id)).rejects.toMatchObject({status:409});});
