const mongoose=require('mongoose');const supertest=require('supertest');const {MongoMemoryServer}=require('mongodb-memory-server');const app=require('../app');const AuditLog=require('../models/AuditLog');const Inventory=require('../models/BloodInventory');const Donation=require('../models/Donation');const BloodRequest=require('../models/BloodRequest');const EmergencyEvent=require('../models/EmergencyEvent');const donationService=require('../services/donationService');const requestService=require('../services/requestService');const emergencyService=require('../services/emergencyAllocationService');const audit=require('../services/auditService');const exportService=require('../services/exportService');const User=require('../models/User');const auth=require('../services/authService');
let mongo;const types=['O-','O+','A-','A+','B-','B+','AB-','AB+'];
let cookie;function request(target){const client=supertest(target);return Object.fromEntries(['get','post','put','patch','delete'].map(method=>[method,(url)=>client[method](url).set('Cookie',cookie).set('X-BloodCare-Request','1')]));}
function binaryParser(res,callback){const chunks=[];res.on('data',chunk=>chunks.push(chunk));res.on('end',()=>callback(null,Buffer.concat(chunks)));}
beforeAll(async()=>{mongo=await MongoMemoryServer.create();await mongoose.connect(mongo.getUri());const passwordHash=await require('bcryptjs').hash(require('node:crypto').randomBytes(20).toString('hex'),12);const user=await User.create({username:'part11-admin',fullName:'Test Admin',email:'part11@example.test',role:'ADMIN',passwordHash});cookie=auth.COOKIE+'='+await auth.issueSession(user);},60000);afterAll(async()=>{await mongoose.disconnect();await mongo.stop();},60000);
beforeEach(async()=>{await Promise.all([AuditLog.deleteMany({}),Inventory.deleteMany({}),Donation.deleteMany({}),BloodRequest.deleteMany({}),EmergencyEvent.deleteMany({})]);await Inventory.insertMany(types.map((bloodType,index)=>({bloodType,unitsAvailable:index===0?10:index+1,reservedUnits:0})));});
test('T01-T02 donation and inventory update create audit entries',async()=>{await donationService.create({donorName:'D-11',bloodType:'A+',unitsDonated:2,status:'AVAILABLE'});expect(await AuditLog.countDocuments({action:audit.ACTIONS.DONATION_CREATED})).toBe(1);const inventoryLog=await AuditLog.findOne({action:audit.ACTIONS.INVENTORY_UPDATED});expect(inventoryLog.newValue.unitsAvailable).toBe(6);});
test('T03 blood request creation and status change are audited',async()=>{const item=await requestService.create({patientReference:'P-11',requiredBloodType:'A+',unitsRequired:1,urgency:'URGENT'});await requestService.updateStatus(item._id,'FULFILLED');expect(await AuditLog.countDocuments({action:audit.ACTIONS.BLOOD_REQUEST_CREATED})).toBe(1);expect((await AuditLog.findOne({action:audit.ACTIONS.BLOOD_REQUEST_UPDATED})).newValue.status).toBe('FULFILLED');});
test('T04 emergency simulation creates audit entry',async()=>{await emergencyService.simulate({eventName:'P11 drill',numberOfCasualties:1,bloodTypeStatus:'ALL_UNKNOWN',estimatedUnitsRequired:2,severity:'CRITICAL',casualtyData:[{casualtyNumber:1,bloodType:'UNKNOWN'}]});expect(await AuditLog.countDocuments({action:audit.ACTIONS.EMERGENCY_SIMULATED})).toBe(1);});
test('T05 emergency confirmation and inventory change are audited',async()=>{const item=await emergencyService.simulate({eventName:'P11 drill',numberOfCasualties:1,bloodTypeStatus:'ALL_UNKNOWN',estimatedUnitsRequired:2,severity:'CRITICAL',casualtyData:[{casualtyNumber:1,bloodType:'UNKNOWN'}]});await emergencyService.confirm(item._id);expect(await AuditLog.countDocuments({action:audit.ACTIONS.EMERGENCY_CONFIRMED})).toBe(1);expect(await AuditLog.countDocuments({action:audit.ACTIONS.EMERGENCY_INVENTORY_UPDATED})).toBe(1);});
test('T06 audit endpoint returns newest first',async()=>{await audit.createAuditLog({action:'OLD',entityType:'TEST',description:'old',timestamp:new Date('2026-01-01')});await audit.createAuditLog({action:'NEW',entityType:'TEST',description:'new',timestamp:new Date('2026-02-01')});const r=await request(app).get('/api/audit');expect(r.status).toBe(200);expect(r.body.data.items.map(x=>x.action)).toEqual(['NEW','OLD']);});
test('T07 audit action filtering works',async()=>{await audit.createAuditLog({action:'ONE',entityType:'TEST',description:'one'});await audit.createAuditLog({action:'TWO',entityType:'TEST',description:'two'});const r=await request(app).get('/api/audit?action=ONE');expect(r.body.data.items).toHaveLength(1);expect(r.body.data.items[0].action).toBe('ONE');});
test('T08 audit entity filtering works',async()=>{await audit.createAuditLog({action:'ONE',entityType:'DONATION',description:'one'});await audit.createAuditLog({action:'ONE',entityType:'SYSTEM',description:'two'});const r=await request(app).get('/api/audit?entityType=SYSTEM');expect(r.body.data.items).toHaveLength(1);});
test('T09 audit date filtering works',async()=>{await audit.createAuditLog({action:'JAN',entityType:'TEST',description:'jan',timestamp:new Date('2026-01-01')});await audit.createAuditLog({action:'FEB',entityType:'TEST',description:'feb',timestamp:new Date('2026-02-01')});const r=await request(app).get('/api/audit?startDate=2026-02-01&endDate=2026-02-01');expect(r.body.data.items.map(x=>x.action)).toEqual(['FEB']);});
test('T10 audit records cannot be modified through API',async()=>{const item=await audit.createAuditLog({action:'LOCKED',entityType:'TEST',description:'append only'});expect((await request(app).put(`/api/audit/${item._id}`).send({description:'changed'})).status).toBe(404);expect((await request(app).delete(`/api/audit/${item._id}`)).status).toBe(404);expect((await AuditLog.findById(item._id)).description).toBe('append only');});
test('T11-T14 metadata CSV returns inventory, counts, and audit record',async()=>{await Donation.create({donorName:'D',bloodType:'O+',unitsDonated:1});await BloodRequest.create({patientReference:'P',requiredBloodType:'O-',unitsRequired:1,urgency:'URGENT'});await EmergencyEvent.create({eventName:'E',numberOfCasualties:1,bloodTypeStatus:'ALL_UNKNOWN',estimatedUnitsRequired:1,severity:'URGENT',casualtyData:[{casualtyNumber:1,bloodType:'UNKNOWN',unitsRequired:1}],allocation:[],inventorySnapshot:[],totalAllocated:0,shortage:1,warnings:[],allocationStatus:'CRITICAL_SHORTAGE'});const r=await request(app).get('/api/exports/becs-metadata?format=csv');expect(r.status).toBe(200);expect(r.headers['content-type']).toMatch(/text\/csv/);expect(r.text).toContain('CURRENT INVENTORY SNAPSHOT,O-,10,0,LOW');expect(r.text).toContain('Total donations,,,,1');expect(r.text).toContain('Total blood requests,,,,1');expect(r.text).toContain('Total emergency events,,,,1');expect(await AuditLog.countDocuments({action:audit.ACTIONS.BECS_METADATA_EXPORTED})).toBe(1);});
test('T15-T18 filtered audit export contains correct rows and audits export',async()=>{await audit.createAuditLog({action:'KEEP',entityType:'TEST',entityId:'1',description:'included'});await audit.createAuditLog({action:'SKIP',entityType:'TEST',entityId:'2',description:'excluded'});const r=await request(app).get('/api/exports/audit-trail?format=csv&action=KEEP');expect(r.status).toBe(200);expect(r.text).toContain('Timestamp,Action,Entity Type,Entity ID,Description,Performed By,Old Value,New Value');expect(r.text).toContain('KEEP,TEST,1,included');expect(r.text).not.toContain('SKIP,TEST,2,excluded');const log=await AuditLog.findOne({action:audit.ACTIONS.AUDIT_TRAIL_EXPORTED});expect(log.metadata.recordCount).toBe(1);});
test('T19 exports do not modify inventory',async()=>{const before=await Inventory.find().sort({bloodType:1}).lean();await exportService.becsMetadata();await exportService.auditTrail();const after=await Inventory.find().sort({bloodType:1}).lean();expect(after.map(x=>[x.bloodType,x.unitsAvailable,x.reservedUnits])).toEqual(before.map(x=>[x.bloodType,x.unitsAvailable,x.reservedUnits]));});
test('T20 CSV escaping and headers are correct',()=>{expect(exportService.escapeCsv('a,"b"\nline')).toBe('"a,""b""\nline"');expect(exportService.csv(['A','B'],[['x','y']])).toBe('\uFEFFA,B\r\nx,y');});
test.each([
  ['/api/exports/becs-metadata?format=xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','.xlsx','PK'],
  ['/api/exports/becs-metadata?format=pdf','application/pdf','.pdf','%PDF-'],
  ['/api/exports/audit-trail?format=xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','.xlsx','PK'],
  ['/api/exports/audit-trail?format=pdf','application/pdf','.pdf','%PDF-']
])('T21 binary export %s has a valid attachment signature',async(url,contentType,extension,signature)=>{const r=await request(app).get(url).buffer(true).parse(binaryParser);expect(r.status).toBe(200);expect(r.headers['content-type']).toContain(contentType);expect(r.headers['content-disposition']).toContain(extension);expect(r.body.subarray(0,signature.length).toString()).toBe(signature);expect(r.body.length).toBeGreaterThan(1000);});
test('T22 unsupported export format is rejected',async()=>{const r=await request(app).get('/api/exports/becs-metadata?format=docx');expect(r.status).toBe(400);expect(r.body.errors[0]).toBe('Format must be csv, xlsx, or pdf');});
test('T23 empty optional audit filters are ignored',async()=>{const r=await request(app).get('/api/audit?action=&entityType=DONATION&startDate=&endDate=&page=1&limit=10');expect(r.status).toBe(200);expect(r.body.success).toBe(true);});
